name: Upload to Maven Packages

on:
  push:
    branches:
    - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Install CraftBukkit 1.8
      uses: SpraxDev/Action-SpigotMC@v4
      with:
        versions: 1.8.8

    - name: Build with Maven
      run: mvn dependency:purge-local-repository -U -B package --file pom.xml
      
    - name: Add Jar to GitHub releases
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.PASSWORD }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Automatic Build from Pull Request"
        files: |
          target/*.jar
          
    - name: Publish to GitHub Packages Apache Maven
      env:
        GITHUB_USERNAME: ${{ secrets.USERNAME }}
        GITHUB_TOKEN: ${{ secrets.PASSWORD }}
      run: mvn -DuseGitHubPackages=true --settings $GITHUB_WORKSPACE/settings.xml deploy
